import localFont from "next/font/local";
import "./globals.css";
import { WalletProvider } from "./Context/wallet";
import Background from "../../components/background";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "ChETH Funds",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Background className="absolute top-0 -z-20" />
        <WalletProvider>
        <div className="-mt-[100vh] z-40">
          {children}
          </div>
        </WalletProvider>
      </body>
    </html>
  );
}
